# Generated by Django 3.2.25 on 2025-12-04 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createblog',
            name='date',
        ),
        migrations.AddField(
            model_name='createblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createblog',
            name='content',
            field=models.TextField(),
        ),
    ]
